twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic   : cmd_vel
        timeout : 0.0
        priority: 10
      joystick:
        topic   : cmd_vel_key
        timeout : 0.0
        priority: 100
      avoidance:
        topic   : cmd_vel_avoidance
        timeout : 0.5
        priority: 200
